wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1660017736.861697
    t:
      1:
      - 1
      - 37
      - 38
      - 41
      - 55
      2:
      - 1
      - 37
      - 38
      - 41
      - 55
      3:
      - 13
      - 23
      4: 3.9.12
      5: 0.13.1
      8:
      - 5
